// Curated mock recipe catalog, hand-compiled from common/public recipe knowledge
// for local development and testing (search filters, pantry matching, grocery
// consolidation) — NOT scraped live, and nutrition figures are rough estimates,
// not verified nutrition-label data. Replace/expand freely; see CLAUDE.md.

export type SeedIngredient = {
  name: string;
  category:
    | "produce"
    | "dairy"
    | "meat"
    | "seafood"
    | "grains"
    | "pantry"
    | "spices"
    | "other";
  amount: number | null;
  unit: string | null;
  note?: string | null;
};

export type SeedRecipe = {
  title: string;
  cuisine: string;
  servings: number;
  dietTags: string[];
  instructions: string[];
  nutrition: { calories: number; protein: number; carbs: number; fat: number };
  ingredients: SeedIngredient[];
};

export const seedRecipes: SeedRecipe[] = [
  {
    title: "Spaghetti Aglio e Olio",
    cuisine: "Italian",
    servings: 4,
    dietTags: ["vegetarian", "vegan", "dairy-free"],
    nutrition: { calories: 420, protein: 11, carbs: 62, fat: 14 },
    instructions: [
      "Cook spaghetti in salted boiling water until al dente; reserve 1 cup pasta water.",
      "Warm olive oil in a large pan over low heat, add sliced garlic and red pepper flakes, cook until golden.",
      "Toss drained pasta into the pan with a splash of pasta water, parsley, and salt to taste.",
    ],
    ingredients: [
      { name: "spaghetti", category: "grains", amount: 1, unit: "lb", note: null },
      { name: "olive oil", category: "pantry", amount: 0.5, unit: "cup", note: null },
      { name: "garlic", category: "produce", amount: 6, unit: "clove", note: "sliced" },
      { name: "red pepper flakes", category: "spices", amount: 1, unit: "tsp", note: null },
      { name: "parsley", category: "produce", amount: 0.25, unit: "cup", note: "chopped" },
      { name: "salt", category: "spices", amount: null, unit: null, note: "to taste" },
    ],
  },
  {
    title: "Chicken Stir Fry",
    cuisine: "Asian",
    servings: 4,
    dietTags: ["dairy-free"],
    nutrition: { calories: 380, protein: 34, carbs: 24, fat: 15 },
    instructions: [
      "Slice chicken breast thin and marinate in soy sauce and cornstarch for 10 minutes.",
      "Stir-fry chicken in hot oil until browned; remove from pan.",
      "Stir-fry broccoli, carrot, and bell pepper until crisp-tender; add garlic and ginger.",
      "Return chicken to pan, add soy sauce and sesame oil, toss to combine.",
    ],
    ingredients: [
      { name: "chicken breast", category: "meat", amount: 1.5, unit: "lb", note: "sliced" },
      { name: "broccoli", category: "produce", amount: 2, unit: "cup", note: "florets" },
      { name: "carrot", category: "produce", amount: 2, unit: "whole", note: "sliced" },
      { name: "bell pepper", category: "produce", amount: 1, unit: "whole", note: "sliced" },
      { name: "garlic", category: "produce", amount: 3, unit: "clove", note: "minced" },
      { name: "ginger", category: "produce", amount: 1, unit: "tbsp", note: "minced" },
      { name: "soy sauce", category: "pantry", amount: 4, unit: "tbsp", note: null },
      { name: "cornstarch", category: "pantry", amount: 1, unit: "tbsp", note: null },
      { name: "sesame oil", category: "pantry", amount: 1, unit: "tbsp", note: null },
      { name: "vegetable oil", category: "pantry", amount: 2, unit: "tbsp", note: null },
    ],
  },
  {
    title: "Black Bean Tacos",
    cuisine: "Mexican",
    servings: 4,
    dietTags: ["vegetarian", "vegan", "dairy-free", "gluten-free"],
    nutrition: { calories: 340, protein: 13, carbs: 52, fat: 9 },
    instructions: [
      "Sauté onion and garlic in oil until soft; add cumin and chili powder.",
      "Add black beans and a splash of water, simmer 10 minutes, mash slightly.",
      "Warm corn tortillas, fill with beans, top with avocado, cilantro, and lime.",
    ],
    ingredients: [
      { name: "black beans", category: "pantry", amount: 2, unit: "can", note: "drained" },
      { name: "corn tortillas", category: "grains", amount: 8, unit: "whole", note: null },
      { name: "onion", category: "produce", amount: 1, unit: "whole", note: "diced" },
      { name: "garlic", category: "produce", amount: 2, unit: "clove", note: "minced" },
      { name: "cumin", category: "spices", amount: 1, unit: "tsp", note: null },
      { name: "chili powder", category: "spices", amount: 1, unit: "tsp", note: null },
      { name: "avocado", category: "produce", amount: 1, unit: "whole", note: "sliced" },
      { name: "cilantro", category: "produce", amount: 0.25, unit: "cup", note: "chopped" },
      { name: "lime", category: "produce", amount: 1, unit: "whole", note: "wedges" },
      { name: "olive oil", category: "pantry", amount: 1, unit: "tbsp", note: null },
    ],
  },
  {
    title: "Greek Chickpea Salad",
    cuisine: "Mediterranean",
    servings: 4,
    dietTags: ["vegetarian", "gluten-free"],
    nutrition: { calories: 310, protein: 11, carbs: 30, fat: 17 },
    instructions: [
      "Combine chickpeas, cucumber, tomato, red onion, and feta in a bowl.",
      "Whisk olive oil, lemon juice, oregano, salt, and pepper for dressing.",
      "Toss salad with dressing and top with kalamata olives.",
    ],
    ingredients: [
      { name: "chickpeas", category: "pantry", amount: 2, unit: "can", note: "drained" },
      { name: "cucumber", category: "produce", amount: 1, unit: "whole", note: "diced" },
      { name: "tomato", category: "produce", amount: 2, unit: "whole", note: "diced" },
      { name: "red onion", category: "produce", amount: 0.5, unit: "whole", note: "sliced" },
      { name: "feta cheese", category: "dairy", amount: 0.5, unit: "cup", note: "crumbled" },
      { name: "kalamata olives", category: "pantry", amount: 0.5, unit: "cup", note: null },
      { name: "olive oil", category: "pantry", amount: 3, unit: "tbsp", note: null },
      { name: "lemon", category: "produce", amount: 1, unit: "whole", note: "juiced" },
      { name: "oregano", category: "spices", amount: 1, unit: "tsp", note: "dried" },
    ],
  },
  {
    title: "Chicken Tikka Masala",
    cuisine: "Indian",
    servings: 4,
    dietTags: ["gluten-free"],
    nutrition: { calories: 460, protein: 32, carbs: 18, fat: 28 },
    instructions: [
      "Marinate cubed chicken in yogurt, garam masala, and turmeric for at least 30 minutes.",
      "Sear chicken until browned; set aside.",
      "Sauté onion, garlic, and ginger; add tomato puree and simmer.",
      "Stir in cream and chicken, simmer until cooked through, finish with cilantro.",
    ],
    ingredients: [
      { name: "chicken breast", category: "meat", amount: 1.5, unit: "lb", note: "cubed" },
      { name: "yogurt", category: "dairy", amount: 0.5, unit: "cup", note: "plain" },
      { name: "garam masala", category: "spices", amount: 2, unit: "tsp", note: null },
      { name: "turmeric", category: "spices", amount: 1, unit: "tsp", note: null },
      { name: "onion", category: "produce", amount: 1, unit: "whole", note: "diced" },
      { name: "garlic", category: "produce", amount: 3, unit: "clove", note: "minced" },
      { name: "ginger", category: "produce", amount: 1, unit: "tbsp", note: "minced" },
      { name: "tomato puree", category: "pantry", amount: 2, unit: "cup", note: null },
      { name: "heavy cream", category: "dairy", amount: 0.5, unit: "cup", note: null },
      { name: "cilantro", category: "produce", amount: 0.25, unit: "cup", note: "chopped" },
    ],
  },
  {
    title: "Vegetable Fried Rice",
    cuisine: "Asian",
    servings: 4,
    dietTags: ["vegetarian", "dairy-free"],
    nutrition: { calories: 360, protein: 10, carbs: 55, fat: 11 },
    instructions: [
      "Scramble eggs in a hot wok, remove and set aside.",
      "Stir-fry carrot, peas, and onion in oil until tender.",
      "Add cold rice, breaking up clumps, stir-fry until heated through.",
      "Add soy sauce, scrambled eggs, and green onion, toss to combine.",
    ],
    ingredients: [
      { name: "cooked rice", category: "grains", amount: 4, unit: "cup", note: "cold, day-old" },
      { name: "egg", category: "dairy", amount: 3, unit: "whole", note: null },
      { name: "carrot", category: "produce", amount: 1, unit: "whole", note: "diced" },
      { name: "peas", category: "produce", amount: 1, unit: "cup", note: "frozen" },
      { name: "onion", category: "produce", amount: 0.5, unit: "whole", note: "diced" },
      { name: "green onion", category: "produce", amount: 2, unit: "whole", note: "sliced" },
      { name: "soy sauce", category: "pantry", amount: 3, unit: "tbsp", note: null },
      { name: "vegetable oil", category: "pantry", amount: 2, unit: "tbsp", note: null },
    ],
  },
  {
    title: "Turkey Chili",
    cuisine: "American",
    servings: 6,
    dietTags: ["gluten-free", "dairy-free"],
    nutrition: { calories: 320, protein: 28, carbs: 30, fat: 10 },
    instructions: [
      "Brown ground turkey with onion and garlic in a large pot.",
      "Add chili powder, cumin, diced tomatoes, and kidney beans.",
      "Simmer uncovered for 30 minutes, stirring occasionally.",
    ],
    ingredients: [
      { name: "ground turkey", category: "meat", amount: 1.5, unit: "lb", note: null },
      { name: "onion", category: "produce", amount: 1, unit: "whole", note: "diced" },
      { name: "garlic", category: "produce", amount: 3, unit: "clove", note: "minced" },
      { name: "diced tomatoes", category: "pantry", amount: 2, unit: "can", note: null },
      { name: "kidney beans", category: "pantry", amount: 2, unit: "can", note: "drained" },
      { name: "chili powder", category: "spices", amount: 2, unit: "tbsp", note: null },
      { name: "cumin", category: "spices", amount: 1, unit: "tbsp", note: null },
    ],
  },
  {
    title: "Baked Salmon with Roasted Vegetables",
    cuisine: "American",
    servings: 4,
    dietTags: ["gluten-free", "dairy-free", "keto", "pescatarian"],
    nutrition: { calories: 410, protein: 36, carbs: 12, fat: 24 },
    instructions: [
      "Toss broccoli and asparagus with olive oil, salt, and pepper; spread on a sheet pan.",
      "Place salmon fillets on the pan, drizzle with lemon and olive oil.",
      "Roast at 400°F for 15-18 minutes until salmon flakes easily.",
    ],
    ingredients: [
      { name: "salmon fillet", category: "seafood", amount: 4, unit: "piece", note: "6 oz each" },
      { name: "broccoli", category: "produce", amount: 2, unit: "cup", note: "florets" },
      { name: "asparagus", category: "produce", amount: 1, unit: "bunch", note: "trimmed" },
      { name: "olive oil", category: "pantry", amount: 3, unit: "tbsp", note: null },
      { name: "lemon", category: "produce", amount: 1, unit: "whole", note: "sliced" },
      { name: "salt", category: "spices", amount: null, unit: null, note: "to taste" },
      { name: "black pepper", category: "spices", amount: null, unit: null, note: "to taste" },
    ],
  },
  {
    title: "Caprese Pasta Salad",
    cuisine: "Italian",
    servings: 4,
    dietTags: ["vegetarian"],
    nutrition: { calories: 390, protein: 14, carbs: 45, fat: 17 },
    instructions: [
      "Cook pasta until al dente, drain and cool.",
      "Combine pasta with cherry tomatoes, mozzarella pearls, and basil.",
      "Toss with olive oil, balsamic glaze, salt, and pepper.",
    ],
    ingredients: [
      { name: "pasta", category: "grains", amount: 12, unit: "oz", note: "short shape" },
      { name: "cherry tomatoes", category: "produce", amount: 2, unit: "cup", note: "halved" },
      { name: "mozzarella pearls", category: "dairy", amount: 8, unit: "oz", note: null },
      { name: "basil", category: "produce", amount: 0.5, unit: "cup", note: "torn" },
      { name: "olive oil", category: "pantry", amount: 3, unit: "tbsp", note: null },
      { name: "balsamic glaze", category: "pantry", amount: 2, unit: "tbsp", note: null },
      { name: "salt", category: "spices", amount: null, unit: null, note: "to taste" },
    ],
  },
  {
    title: "Beef and Broccoli",
    cuisine: "Asian",
    servings: 4,
    dietTags: ["gluten-free", "dairy-free"],
    nutrition: { calories: 400, protein: 30, carbs: 20, fat: 22 },
    instructions: [
      "Slice beef thin against the grain, marinate in soy sauce and cornstarch.",
      "Sear beef in hot oil until browned; remove from pan.",
      "Stir-fry broccoli with garlic until crisp-tender.",
      "Return beef to pan with sauce (soy sauce, oyster sauce, brown sugar), toss until glazed.",
    ],
    ingredients: [
      { name: "flank steak", category: "meat", amount: 1.5, unit: "lb", note: "thin sliced" },
      { name: "broccoli", category: "produce", amount: 3, unit: "cup", note: "florets" },
      { name: "garlic", category: "produce", amount: 3, unit: "clove", note: "minced" },
      { name: "soy sauce", category: "pantry", amount: 4, unit: "tbsp", note: null },
      { name: "oyster sauce", category: "pantry", amount: 2, unit: "tbsp", note: null },
      { name: "brown sugar", category: "pantry", amount: 1, unit: "tbsp", note: null },
      { name: "cornstarch", category: "pantry", amount: 1, unit: "tbsp", note: null },
      { name: "vegetable oil", category: "pantry", amount: 2, unit: "tbsp", note: null },
    ],
  },
  {
    title: "Lentil Soup",
    cuisine: "Mediterranean",
    servings: 6,
    dietTags: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    nutrition: { calories: 260, protein: 15, carbs: 40, fat: 5 },
    instructions: [
      "Sauté onion, carrot, celery, and garlic in olive oil until softened.",
      "Add lentils, diced tomatoes, cumin, and vegetable broth; bring to a boil.",
      "Simmer 25-30 minutes until lentils are tender; season with lemon juice.",
    ],
    ingredients: [
      { name: "green lentils", category: "pantry", amount: 2, unit: "cup", note: "dried" },
      { name: "onion", category: "produce", amount: 1, unit: "whole", note: "diced" },
      { name: "carrot", category: "produce", amount: 2, unit: "whole", note: "diced" },
      { name: "celery", category: "produce", amount: 2, unit: "stalk", note: "diced" },
      { name: "garlic", category: "produce", amount: 3, unit: "clove", note: "minced" },
      { name: "diced tomatoes", category: "pantry", amount: 1, unit: "can", note: null },
      { name: "vegetable broth", category: "pantry", amount: 6, unit: "cup", note: null },
      { name: "cumin", category: "spices", amount: 1, unit: "tsp", note: null },
      { name: "olive oil", category: "pantry", amount: 2, unit: "tbsp", note: null },
      { name: "lemon", category: "produce", amount: 1, unit: "whole", note: "juiced" },
    ],
  },
  {
    title: "Shakshuka",
    cuisine: "Middle Eastern",
    servings: 4,
    dietTags: ["vegetarian", "gluten-free"],
    nutrition: { calories: 260, protein: 14, carbs: 16, fat: 16 },
    instructions: [
      "Sauté onion and bell pepper in olive oil until soft; add garlic, cumin, and paprika.",
      "Add crushed tomatoes and simmer 10 minutes until thickened.",
      "Make wells in the sauce, crack eggs into each, cover and cook until whites set.",
      "Top with feta and parsley.",
    ],
    ingredients: [
      { name: "egg", category: "dairy", amount: 6, unit: "whole", note: null },
      { name: "crushed tomatoes", category: "pantry", amount: 1, unit: "can", note: "28 oz" },
      { name: "onion", category: "produce", amount: 1, unit: "whole", note: "diced" },
      { name: "bell pepper", category: "produce", amount: 1, unit: "whole", note: "diced" },
      { name: "garlic", category: "produce", amount: 3, unit: "clove", note: "minced" },
      { name: "cumin", category: "spices", amount: 1, unit: "tsp", note: null },
      { name: "paprika", category: "spices", amount: 1, unit: "tsp", note: null },
      { name: "feta cheese", category: "dairy", amount: 0.33, unit: "cup", note: "crumbled" },
      { name: "parsley", category: "produce", amount: 0.25, unit: "cup", note: "chopped" },
      { name: "olive oil", category: "pantry", amount: 2, unit: "tbsp", note: null },
    ],
  },
  {
    title: "Chicken Caesar Wrap",
    cuisine: "American",
    servings: 4,
    dietTags: [],
    nutrition: { calories: 450, protein: 30, carbs: 34, fat: 22 },
    instructions: [
      "Grill or pan-sear chicken breast, slice thin.",
      "Toss romaine with caesar dressing and parmesan.",
      "Fill tortillas with chicken and salad, roll tightly.",
    ],
    ingredients: [
      { name: "chicken breast", category: "meat", amount: 1, unit: "lb", note: null },
      { name: "romaine lettuce", category: "produce", amount: 4, unit: "cup", note: "chopped" },
      { name: "caesar dressing", category: "pantry", amount: 0.33, unit: "cup", note: null },
      { name: "parmesan cheese", category: "dairy", amount: 0.25, unit: "cup", note: "grated" },
      { name: "flour tortillas", category: "grains", amount: 4, unit: "whole", note: "large" },
    ],
  },
  {
    title: "Vegetable Curry with Rice",
    cuisine: "Indian",
    servings: 4,
    dietTags: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    nutrition: { calories: 380, protein: 9, carbs: 55, fat: 15 },
    instructions: [
      "Sauté onion, garlic, and ginger in oil; add curry powder and toast briefly.",
      "Add cauliflower, potato, and coconut milk; simmer until vegetables are tender.",
      "Stir in peas and spinach at the end; serve over rice.",
    ],
    ingredients: [
      { name: "cauliflower", category: "produce", amount: 1, unit: "whole", note: "florets" },
      { name: "potato", category: "produce", amount: 2, unit: "whole", note: "diced" },
      { name: "onion", category: "produce", amount: 1, unit: "whole", note: "diced" },
      { name: "garlic", category: "produce", amount: 3, unit: "clove", note: "minced" },
      { name: "ginger", category: "produce", amount: 1, unit: "tbsp", note: "minced" },
      { name: "coconut milk", category: "pantry", amount: 1, unit: "can", note: null },
      { name: "curry powder", category: "spices", amount: 2, unit: "tbsp", note: null },
      { name: "peas", category: "produce", amount: 1, unit: "cup", note: "frozen" },
      { name: "spinach", category: "produce", amount: 2, unit: "cup", note: null },
      { name: "cooked rice", category: "grains", amount: 4, unit: "cup", note: null },
    ],
  },
  {
    title: "Overnight Oats with Berries",
    cuisine: "American",
    servings: 2,
    dietTags: ["vegetarian", "gluten-free"],
    nutrition: { calories: 320, protein: 12, carbs: 50, fat: 8 },
    instructions: [
      "Combine oats, milk, yogurt, and chia seeds in a jar.",
      "Stir in honey, cover, and refrigerate overnight.",
      "Top with fresh berries before serving.",
    ],
    ingredients: [
      { name: "rolled oats", category: "grains", amount: 1, unit: "cup", note: null },
      { name: "milk", category: "dairy", amount: 1, unit: "cup", note: null },
      { name: "yogurt", category: "dairy", amount: 0.5, unit: "cup", note: "plain" },
      { name: "chia seeds", category: "pantry", amount: 2, unit: "tbsp", note: null },
      { name: "honey", category: "pantry", amount: 2, unit: "tbsp", note: null },
      { name: "mixed berries", category: "produce", amount: 1, unit: "cup", note: null },
    ],
  },
  {
    title: "Veggie Egg Scramble",
    cuisine: "American",
    servings: 2,
    dietTags: ["vegetarian", "gluten-free", "keto"],
    nutrition: { calories: 290, protein: 20, carbs: 8, fat: 20 },
    instructions: [
      "Sauté bell pepper, onion, and spinach in butter until softened.",
      "Add beaten eggs, scramble gently until just set.",
      "Top with shredded cheddar and serve.",
    ],
    ingredients: [
      { name: "egg", category: "dairy", amount: 5, unit: "whole", note: null },
      { name: "bell pepper", category: "produce", amount: 0.5, unit: "whole", note: "diced" },
      { name: "onion", category: "produce", amount: 0.25, unit: "whole", note: "diced" },
      { name: "spinach", category: "produce", amount: 1, unit: "cup", note: null },
      { name: "cheddar cheese", category: "dairy", amount: 0.25, unit: "cup", note: "shredded" },
      { name: "butter", category: "dairy", amount: 1, unit: "tbsp", note: null },
    ],
  },
  {
    title: "Quinoa Buddha Bowl",
    cuisine: "American",
    servings: 4,
    dietTags: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
    nutrition: { calories: 400, protein: 13, carbs: 52, fat: 17 },
    instructions: [
      "Cook quinoa according to package directions.",
      "Roast sweet potato and chickpeas with olive oil and paprika at 425°F for 25 minutes.",
      "Assemble bowls with quinoa, roasted vegetables, avocado, and tahini dressing.",
    ],
    ingredients: [
      { name: "quinoa", category: "grains", amount: 1.5, unit: "cup", note: "uncooked" },
      { name: "sweet potato", category: "produce", amount: 2, unit: "whole", note: "cubed" },
      { name: "chickpeas", category: "pantry", amount: 1, unit: "can", note: "drained" },
      { name: "avocado", category: "produce", amount: 1, unit: "whole", note: "sliced" },
      { name: "tahini", category: "pantry", amount: 3, unit: "tbsp", note: null },
      { name: "paprika", category: "spices", amount: 1, unit: "tsp", note: null },
      { name: "olive oil", category: "pantry", amount: 2, unit: "tbsp", note: null },
      { name: "lemon", category: "produce", amount: 1, unit: "whole", note: "juiced" },
    ],
  },
  {
    title: "Beef Tacos",
    cuisine: "Mexican",
    servings: 4,
    dietTags: [],
    nutrition: { calories: 420, protein: 25, carbs: 30, fat: 22 },
    instructions: [
      "Brown ground beef with onion; drain excess fat.",
      "Add taco seasoning and a splash of water, simmer 5 minutes.",
      "Fill taco shells with beef, lettuce, tomato, cheese, and salsa.",
    ],
    ingredients: [
      { name: "ground beef", category: "meat", amount: 1.5, unit: "lb", note: null },
      { name: "onion", category: "produce", amount: 0.5, unit: "whole", note: "diced" },
      { name: "taco seasoning", category: "spices", amount: 2, unit: "tbsp", note: null },
      { name: "taco shells", category: "grains", amount: 8, unit: "whole", note: null },
      { name: "lettuce", category: "produce", amount: 1, unit: "cup", note: "shredded" },
      { name: "tomato", category: "produce", amount: 1, unit: "whole", note: "diced" },
      { name: "cheddar cheese", category: "dairy", amount: 0.5, unit: "cup", note: "shredded" },
      { name: "salsa", category: "pantry", amount: 0.5, unit: "cup", note: null },
    ],
  },
  {
    title: "Baked Cod with Lemon",
    cuisine: "Mediterranean",
    servings: 4,
    dietTags: ["gluten-free", "dairy-free", "keto", "pescatarian"],
    nutrition: { calories: 220, protein: 32, carbs: 4, fat: 8 },
    instructions: [
      "Place cod fillets in a baking dish, drizzle with olive oil and lemon juice.",
      "Season with garlic, salt, and pepper, top with lemon slices.",
      "Bake at 400°F for 12-15 minutes until fish flakes easily.",
    ],
    ingredients: [
      { name: "cod fillet", category: "seafood", amount: 4, unit: "piece", note: "6 oz each" },
      { name: "olive oil", category: "pantry", amount: 2, unit: "tbsp", note: null },
      { name: "lemon", category: "produce", amount: 2, unit: "whole", note: "sliced and juiced" },
      { name: "garlic", category: "produce", amount: 2, unit: "clove", note: "minced" },
      { name: "salt", category: "spices", amount: null, unit: null, note: "to taste" },
      { name: "black pepper", category: "spices", amount: null, unit: null, note: "to taste" },
    ],
  },
  {
    title: "Margherita Pizza",
    cuisine: "Italian",
    servings: 4,
    dietTags: ["vegetarian"],
    nutrition: { calories: 480, protein: 19, carbs: 58, fat: 18 },
    instructions: [
      "Stretch pizza dough onto a floured surface or pan.",
      "Spread crushed tomatoes, top with torn mozzarella and a drizzle of olive oil.",
      "Bake at 475°F for 12-15 minutes until crust is golden.",
      "Top with fresh basil before serving.",
    ],
    ingredients: [
      { name: "pizza dough", category: "grains", amount: 1, unit: "lb", note: null },
      { name: "crushed tomatoes", category: "pantry", amount: 1, unit: "cup", note: null },
      { name: "mozzarella cheese", category: "dairy", amount: 8, unit: "oz", note: "fresh, torn" },
      { name: "basil", category: "produce", amount: 0.25, unit: "cup", note: "fresh leaves" },
      { name: "olive oil", category: "pantry", amount: 2, unit: "tbsp", note: null },
    ],
  },
];
